### ISSUE TITLE
indy3 reports out of memory

### ISSUE THREAD

**Issue by stsp** [dosemu2/fdpp#147]
This game seems to be not downloadable,
so just a note to myself.
Works perfectly with pc-dos.

**Comment by stsp** [comment]
Broken also with freedos.

**Comment by stsp** [comment]
It appears (wasn't easy at all to find out!)
that it calls `int 21h/4400h`:
http://www.ctyme.com/intr/rb-2820.htm
and doesn't like bit 15 being set on return,
which means the file is remote.
I checked with PC-DOS, and indeed, it
doesn't set that bit for remote files!
So the meaning of "remote" might be
something different...

Andrew, could you please add some
test for this for various DOSes?
I wonder if no DOS at all would identify
the mfs files as remote?
Which would just mean an RBIL mistake.

**Comment by stsp** [comment]
Hmm, I'll just copy/paste the dosbox code
here:
```
        case 0x00:              /* Get Device Information */
                if (Files[handle]->GetInformation() & 0x8000) { //Check for device
                        reg_dx=Files[handle]->GetInformation();
                } else {
                        Bit8u hdrive=Files[handle]->GetDrive();
                        if (hdrive==0xff) {
                                LOG(LOG_IOCTL,LOG_NORMAL)("00:No drive set");
                                hdrive=2;       // defaulting to C:
                        }
                        /* return drive number in lower 5 bits for block devices
 */
                        reg_dx=(Files[handle]->GetInformation()&0xffe0)|hdrive;
                }
                reg_ax=reg_dx; //Destroyed officially
                return true;
```

This can mean 1 of:
- RBIL confuses the bits 7 and 15
- dosbox made a "mistake"

Well... so RBIL confuses bits?
@bartoldeman what do you think?
Should I just swap bits 7 and 15 in fdpp?

**Comment by stsp** [comment]
Well, given that PC-DOS seems to
always return 0x42, just swapping bits
is not the right solution too.
From dosbox sources it seems like
the bit 7 just mirrors bit 15.

**Comment by stsp** [comment]
Also patch 207ff8f1 by @bartoldeman introduces
the infinite recursion:
```
#11 0x00007ffff6cabb54 in read_char_sft_dev (sft_in=3, sft_out=3, 
    pdev=0x7fff71286630, check_break=1) at chario.cc:335
#12 0x00007ffff6cab9d2 in read_char (sft_in=3, sft_out=3, check_break=1)
    at chario.cc:358
#13 0x00007ffff6cac7de in read_char_check_break (sft_in=3, sft_out=3)
    at chario.cc:363
#14 0x00007ffff6cabdba in read_line (sft_in=3, sft_out=3, kp=...)
    at chario.cc:391
#15 0x00007ffff6caca1f in read_line_handle (sft_idx=3, n=1, bp=...)
    at chario.cc:540
#16 0x00007ffff6cb28b1 in DosRWSft (sft_idx=3, n=1, bp=..., mode=1)
    at dosfns.cc:223
#17 0x00007ffff6cabbb3 in read_char_sft_dev (sft_in=3, sft_out=3, 
    pdev=0x7fff71286fb0, check_break=1) at chario.cc:335
#18 0x00007ffff6cab9d2 in read_char (sft_in=3, sft_out=3, check_break=1)
    at chario.cc:358
#19 0x00007ffff6cac7de in read_char_check_break (sft_in=3, sft_out=3)
    at chario.cc:363
#20 0x00007ffff6cabdba in read_line (sft_in=3, sft_out=3, kp=...)
    at chario.cc:391
#21 0x00007ffff6caca1f in read_line_handle (sft_idx=3, n=1, bp=...)
    at chario.cc:540
#22 0x00007ffff6cb28b1 in DosRWSft (sft_idx=3, n=1, bp=..., mode=1)
    at dosfns.cc:223
```

IMHO read_char_sft_dev() should not
go back to DosRWSft(), as DosRWSft()
calls it too.

**Comment by stsp** [comment]
DRDOS has this fix-up:
```
        mov     ah,0                    ; files/networks return 0 in AH/DH
```
So RBIL bug.

**Comment by stsp** [comment]
Bart, would you like to suggest a fix
for a possible recursion above?
Otherwise I am going to apply something
like a6cc2bdf, which is definitely not correct.
