### ISSUE TITLE
rmdir of RDONLY directory on FAT is denied

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/fdpp#161]
Whilst testing out the ATTRs work on Dosemu2, I discovered a problem with the FAT code inherited from FreeDOS. If a directory has the RDONLY ATTR bit set rmdir is denied. Testing the same scenario on DR-DOS 7.01 and MS-DOS 6.22 the rmdir succeeds.

Here is a temporary testcase (it probably won't be added to Dosemu2 in its current form) that runs on Dosemu2. Here is the output

~~~
$ python test/test_dos.py test_fat_sfn_perms_check_rmdir
Test DR-DOS-7.01 FAT SFN Permission check on rmdir                               ... ok (  2.45s)
Test FR-DOS-1.20 FAT SFN Permission check on rmdir                               ... FAIL
Test MS-DOS-6.22 FAT SFN Permission check on rmdir                               ... ok (  2.76s)
Test PP-DOS-GIT FAT SFN Permission check on rmdir                                ... FAIL

======================================================================
FAIL: Test FR-DOS-1.20 FAT SFN Permission check on rmdir                              
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dos.py", line 4863, in test_fat_sfn_perms_check_rmdir
    perms_check_rmdir(self, "FAT", "SFN")
  File "/clients/common/dosemu2.git/test/func_perms_check_rmdir.py", line 81, in perms_check_rmdir
    self.assertNotIn("FAIL:", results)
AssertionError: 'FAIL:' unexpectedly found in "testit.bat\r\nC:\\>d:\r\nD:\\>set LFN=n\r\nD:\\>c:\\defattr\r\nINFO: Mkdir = 'DIR_RO', err=0\r\nINFO: Getfattr attr=0x11\r\nFAIL: Rmdir failed, err=-1\r\nD:\\>"
Further info in file 'test_dos.FRDOS120TestCase.test_fat_sfn_perms_check_rmdir.log'
Further info in file 'test_dos.FRDOS120TestCase.test_fat_sfn_perms_check_rmdir.xpt'

======================================================================
FAIL: Test PP-DOS-GIT FAT SFN Permission check on rmdir                               
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dos.py", line 4863, in test_fat_sfn_perms_check_rmdir
    perms_check_rmdir(self, "FAT", "SFN")
  File "/clients/common/dosemu2.git/test/func_perms_check_rmdir.py", line 81, in perms_check_rmdir
    self.assertNotIn("FAIL:", results)
AssertionError: 'FAIL:' unexpectedly found in "testit.bat\r\r\n\r\r\nC:\\>d:\r\r\nD:\\>set LFN=n\r\r\nD:\\>c:\\defattr\r\r\nINFO: Mkdir = 'DIR_RO', err=0\r\nINFO: Getfattr attr=0x11\r\nFAIL: Rmdir failed, err=-1\r\n\r\r\nD:\\>"
Further info in file 'test_dos.PPDOSGITTestCase.test_fat_sfn_perms_check_rmdir.log'
Further info in file 'test_dos.PPDOSGITTestCase.test_fat_sfn_perms_check_rmdir.xpt'

----------------------------------------------------------------------
Ran 4 tests in 9.554s

FAILED (failures=2)
~~~

Here is the interesting section from the FDPP expect log
~~~
C:\>testit.bat                                                                  
testit.bat

C:\>d:
D:\>set LFN=n
D:\>c:\defattr
INFO: Mkdir = 'DIR_RO', err=0                                                   
INFO: Getfattr attr=0x11                                                        
FAIL: Rmdir failed, err=-1                                                      

D:\>rem end
~~~
So the `rmdir()` fails with `-1`

Here is the testcase
https://github.com/andrewbird/dosemu2/tree/test-for-fdpp-issue-01

**Comment by stsp** [comment]
Would you like to add a fix?
Doesn't look complicated?
