### ISSUE TITLE
Some FCB tests are now failing

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/fdpp#219]
`test/test_dos.py PPDOSGITTestCase.test_fat_fcb_find_simple`

gives
~~~
ajb@calypso:/clients/common/dosemu2.git$ test/test_dos.py PPDOSGITTestCase.test_fat_fcb_find_simple
Test PP-DOS-GIT  FAT FCB file find simple                                        ... FAIL

======================================================================
FAIL: Test PP-DOS-GIT  FAT FCB file find simple                                       
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_dos.py", line 1549, in test_fat_fcb_find_simple
    self._test_fcb_find_common("FAT", "simple")
  File "/clients/common/dosemu2.git/test/test_dos.py", line 1514, in _test_fcb_find_common
    self.assertIn("(TESTA   BAT)", results)
AssertionError: '(TESTA   BAT)' not found in 'testit.bat\r\r\n\r\r\nC:\\>d:\r\r\nD:\\>c:\\fcbfind1\r\r\nFind Operation Success\r\n(\x00Od��V\x07\x07\x00\x00\x00\x00O)\r\n\r\r\nD:\\>DIR\r\r\n Volume has no label\r\n Directory of d:\\\r\n\r\n2023-04-12 12:34             7 TESTA.BAT\r\n         1 file(s)              7 bytes\r\n         0 dir(s)           10364 KB free\r\nD:\\>'
Further info in file '/clients/common/dosemu2.git/test_dos.PPDOSGITTestCase.test_fat_fcb_find_simple.log'
Further info in file '/clients/common/dosemu2.git/test_dos.PPDOSGITTestCase.test_fat_fcb_find_simple.xpt'

----------------------------------------------------------------------
Ran 1 test in 1.401s

FAILED (failures=1)
~~~

It seems to be returning uninitialised data for the filename/extension part of the FCB

![Screenshot_2023-04-12_12-38-32](https://user-images.githubusercontent.com/220835/231446051-9b9f1b1c-0f27-4563-aed2-12d6fc09f77f.png)

**Comment by stsp** [comment]
Should now be fixed.

**Comment by andrewbird** [comment]
Thanks, looks good to me.
